const ADD_COUNT = 'ADD_COUNT'
const CHANGE_BANNER = 'CHANGE_BANNER'
const CHANGE_RECOMMEND = 'CHANGE_RECOMMEND'
const FETCH_HOME_MULTIDATA = 'FETCH_HOME_MULTIDATA'

export {
    ADD_COUNT,
    CHANGE_BANNER,
    CHANGE_RECOMMEND,
    FETCH_HOME_MULTIDATA
}